# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_42race' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_42race
  pod 'R.swift', '~> 6.0.0'
  pod 'Reusable'
  pod 'SwiftKeychainWrapper'
  pod 'Moya', '~> 15.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Kingfisher', '~> 7.0'
  
  target 'test_42raceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_42raceUITests' do
    # Pods for testing
  end

end
